// Code generated by mockery v1.0.0. DO NOT EDIT.

package gc

import hashmap "github.com/thewizardplusplus/go-hashmap"
import mock "github.com/stretchr/testify/mock"

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

// Delete provides a mock function with given fields: key
func (_m *MockStorage) Delete(key hashmap.Key) {
	_m.Called(key)
}

// Iterate provides a mock function with given fields: handler
func (_m *MockStorage) Iterate(handler hashmap.Handler) bool {
	ret := _m.Called(handler)

	var r0 bool
	if rf, ok := ret.Get(0).(func(hashmap.Handler) bool); ok {
		r0 = rf(handler)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
