// Code generated by mockery v1.0.0. DO NOT EDIT.

package gc

import mock "github.com/stretchr/testify/mock"

// MockGC is an autogenerated mock type for the GC type
type MockGC struct {
	mock.Mock
}

// Clean provides a mock function with given fields:
func (_m *MockGC) Clean() {
	_m.Called()
}
