// Code generated by mockery v1.0.0. DO NOT EDIT.

package cache

import hashmap "github.com/thewizardplusplus/go-hashmap"
import mock "github.com/stretchr/testify/mock"

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

// Delete provides a mock function with given fields: key
func (_m *MockStorage) Delete(key hashmap.Key) {
	_m.Called(key)
}

// Get provides a mock function with given fields: key
func (_m *MockStorage) Get(key hashmap.Key) (interface{}, bool) {
	ret := _m.Called(key)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(hashmap.Key) interface{}); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(hashmap.Key) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Set provides a mock function with given fields: key, data
func (_m *MockStorage) Set(key hashmap.Key, data interface{}) {
	_m.Called(key, data)
}
